# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-argument-parser" = "sha256-JXNjFpLNaqzOGXlIgQtwzG2Yq1daOl4tmTAUcZL4thM=";
    "swift-log" = "sha256-RMG4tekmnK2EdWyuV6pEhke5J79Q3iYMpxweMripZ7I=";
  };
}
