#!/usr/bin/env sh

# Unload the macOS WindowManager process
#launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# We hanlle this with a launch agent. If the Dock is ever restarted, there
# will be sudo-prompt, but that hardly ever happens and this way we don't
# need to mess with the sudoers file.
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
#yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
#yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

#$HOME/.config/yabai/create_spaces.sh

BAR_HEIGHT=$(($(sketchybar -m --query bar | jq -r '.height')+10))

yabai -m config external_bar               all:$BAR_HEIGHT:0     \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.0          \
                active_window_opacity      1.0          \
                normal_window_opacity      0.9          \
                window_border_width        2            \
                window_border_hidpi        off          \
                window_border_radius       11           \
                window_border_blur         off          \
                window_animation_duration  0.3          \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff494d64   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                10           \
                bottom_padding             10            \
                left_padding               10            \
                right_padding              10            \
                window_gap                 6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="CLion" app="CLion" title="Tip of the day|Edit Configuration Settings" manage=off
yabai -m rule --add app="^Orion( RC)?$" title="^Completions$" border=off
yabai -m rule --add title="^Scratchpad" manage=off border=off
# TODO: ideally we would like to filter on level 3
yabai -m rule --add app='^Microsoft Teams( classic)?$" title="^.* \\| Microsoft Teams( classic)?$' manage=off border=off opacity=1

yabai -m config layout bsp

echo "yabai configuration loaded.."

borders &

echo "borders started..."