[package]
name = "maestro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.0", features = ["derive"] }
xdg = "2.5.2"
interprocess = { version = "1.2.1", default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.28.0", features = ["process", "signal"] }