#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
NERD_FONT="Liga SFMono Nerd Font"
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall sketchybar-helper
sketchybar-helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
HEIGHT=30
GROUP_PADDING=15

bar=(
  height=$HEIGHT
  color=0x00000000
  blur_radius=0
  border_width=0
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=0
  padding_left=0
  y_offset=10
  margin=10
  corner_radius=9
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

bracket_defaults=(
  background.height=$HEIGHT
  background.color=$GROUP_BACKGROUND
  background.border_color=$BACKGROUND_2
  background.corner_radius=20
  blur_radius=5
)

sep_defaults=(
  background.border_width=0
  background.padding_left=0
  background.padding_right=5
  label.padding_left=0
  label.padding_right=0
  icon.padding_left=0
  icon.padding_right=0
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"

sketchybar --add bracket appleg apple.logo --set appleg "${bracket_defaults[@]}" background.color=$NIX_LIGHTBLUE background.border_width=0

sketchybar --add item sep.3 left --set sep.3 "${sep_defaults[@]}"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# Center
#source "$ITEM_DIR/spotify.sh"
source "$ITEM_DIR/applemusic.sh"
#source "$ITEM_DIR/media.sh"

sketchybar --add bracket applemusicg applemusic.anchor --set applemusicg "${bracket_defaults[@]}"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/ical.sh"

sketchybar --add bracket calg ical calendar --set calg "${bracket_defaults[@]}"
sketchybar --add item sep.1 right --set sep.1 "${sep_defaults[@]}"

source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/volume.sh"

sketchybar --add bracket sound mic volume volume_icon --set sound "${bracket_defaults[@]}"
sketchybar --add item sep.2 right --set sep.2 "${sep_defaults[@]}"

sketchybar --add item sep.4 right --set sep.4 "${sep_defaults[@]}" background.padding_right=$GROUP_PADDING
source "$ITEM_DIR/battery.sh"
source "$PLUGIN_DIR/stats/item.sh"

sketchybar --add bracket statsg battery cpu.percent memory network.down network.up sep.4 --set statsg "${bracket_defaults[@]}"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
